### ISSUE TITLE
`branch` instead of `targetbranch`

### ISSUE THREAD

**Issue by trans** [theplant/pak#18]
Is it really necessary to be so verbose?

``` yaml
packages:
- name: github.com/theplant/req1
  branch: origin/branch2
- name: github.com/theplant/req2
  branch: origin/branch2
```

A little better I think.
